version: "2"
services:
  postgresql:
    image: docker.io/bitnami/postgresql:13
    container_name: portal_postgress
    restart: unless-stopped
    ports:
      - "5435:5432"
    networks:
      - portal-net
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - portalpostgress:/bitnami/postgresql
      - ./data/pgsql:/var/lib/postgresql/data

  portal_keycloak:
    image: bitnami/keycloak:12.0.4
    container_name: portal-keycloak
    restart: unless-stopped
    ports:
      - "8083:8080"
      - "19993:8443"
    networks:
      - portal-net
    environment:
      - KEYCLOAK_USER=admin_user
      - KEYCLOAK_PASSWORD=admin_password
      - KEYCLOAK_ADMIN=admin_user
      - KEYCLOAK_ADMIN_PASSWORD=admin_password
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - 'KEYCLOAK_JGROUPS_DISCOVERY_PROPERTIES=datasource_jndi_name=>java:jboss/datasources/KeycloakDS, initialize_sql=>"CREATE TABLE IF NOT EXISTS JGROUPSPING ( own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, created timestamp default current_timestamp, ping_data BYTEA, constraint PK_JGROUPSPING PRIMARY KEY (own_addr, cluster_name))"'
      - KEYCLOAK_CACHE_OWNERS_COUNT=3
      - KEYCLOAK_AUTH_CACHE_OWNERS_COUNT=3
    #- KC_HTTP_RELATIVE_PATH=/kc
    #- KC_PROXY=edge
    #- KC_HOSTNAME_STRICT_HTTPS=false
    #- KC_HOSTNAME_STRICT=false
    #- KC_HTTP_ENABLED=true
    # - PROXY_ADDRESS_FORWARDING=true
    volumes:
      - ../../uploads/themes/custom-theme:/opt/bitnami/keycloak/themes/custom-theme
    depends_on:
      - postgresql

volumes:
  portalpostgress:
    driver: local

networks:
  portal-net:
    driver: 'bridge'
    name: portal-net