server:
  port: 8083

spring:
  datasource:
    username: root
    password: Fireburn1!
    url: jdbc:mysql://localhost:3306/user_db?reconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext


keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: bael-admin
      password: pass
    realmImportFile: baeldung-realm.json
    realm: public-library
    resource: spring-boot-app
    auth-server-url: http://localhost:8083/auth
    ssl-required: external
    public-client: true
    principal-attribute: preferred_username

